# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4b647d53ef9bd2fc029d3d5d1b849f4642b129fbd3ac782961ae388659115121330dff50bc46c52b535c178fdbd4051b3f0ffef8dff95a1f7c83024c4d96a35

test:
  secret_key_base: eca04132b4901975b8900e9f8c0cb27ce0c27ea5210494a86c02cc1a72851dd349910ff18b7987e77dea74affd5f3c0f085eca2213209a080d77477d58c3bef7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
